language_model: qwen3.5-flash
query_model: qwen3-max
embedding_model: text-embedding-v4
api_key: your_key
base_url: https://dashscope.aliyuncs.com/compatible-mode/v1


domestic_api_key: your_key
domestic_url: https://apis.tianapi.com/caijing/index
domestic_num: 10



foreign_api_key: your_key
foreign_url: https://real-time-news-data.p.rapidapi.com/full-story-coverage
host: real-time-news-data.p.rapidapi.com
content_type: application/json

graph_url: 127.0.0.1
graph_username: root
graph_password: root
graph_port: 8080
graph_name: hugegraph

